---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dice
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dice
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["watch", "list", "get", "update"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["watch", "list", "get"]
- apiGroups: [""]
  resources: ["pods/eviction"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dice
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dice
subjects:
  - kind: ServiceAccount
    name: dice
    namespace: kube-system
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dice
  namespace: kube-system
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: dice
    spec:
      serviceAccountName: dice
      containers:
      - name: dice
        image: gcr.io/dmathieu-225120/dice-linux-amd64
        command:
          - ./dice
          - loop
          - -c=aws
        env:
          - name: AWS_REGION
            value: us-east-1
        volumeMounts:
          - name: ssl-certs
            mountPath: /etc/ssl/certs/ca-bundle.crt
            readOnly: true
        imagePullPolicy: "Always"
      volumes:
        - name: ssl-certs
          hostPath:
            path: "/etc/ssl/certs/ca-bundle.crt"
